name: deepsdf
channels:
  - pytorch3d
  - pytorch
  - open3d-admin
  - iopath
  - fvcore
  - akode
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - einops=0.4.1
  - h5py
  - matplotlib
  - numpy=1.22.3
  - open3d=0.11.2
  - plyfile=0.7.4
  - python=3.6
  - pytorch=1.10.0
  - pytorch3d=0.6.2
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
  - scipy=1.9.1
  - tensorboardx
  - torchvision=0.11.1
  - annoy
  - point_cloud_utils=0.18.0
  - numpy-stl
  - sympy
  - tqdm
  - trimesh=3.15.3
  - wandb
